language: ruby
sudo: false

jobs:
  include:
    - rvm: 2.4
      gemfile: Gemfile.rails52
    - rvm: 2.7
      gemfile: Gemfile.rails60
    - rvm: 2.7
      gemfile: Gemfile.rails_head

services:
  - mysql
